# Generated by Django 5.1.1 on 2024-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lesson_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url_to_video',
            field=models.URLField(verbose_name='Url to video'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='watched_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
